- hosts: tag_headless-client
  gather_facts: no

  tasks:
    - include_role:
        name: booted

- hosts: tag_headless-client
  become: yes
  become_method: sudo
  strategy: free
  tasks:
    - include_role:
        name: headless_client
      vars:
        arma_host: 66.151.244.237
        mods:
          - "@ace"
          - "@ace_cpr"
          - "@advancedurbanrappelling"
          - "@bc"
          - "@cba_a3"
          - "@cupcore"
          - "@cupcwa"
          - "@cupmaps"
          - "@em"
          - "@jsrs"
          - "@popfor"
          - "@spec4gear"
          - "@stui"
          - "@task_force_radio"
          - "@tryk"
          - "optional/@ares"
          - "rhs/@rhsafrf"
          - "rhs/@rhsgref"
          - "rhs/@rhssaf"
          - "rhs/@rhsusaf"
