- hosts: tag_headless-client
  gather_facts: no

  tasks:
    - include_role:
        name: booted

- hosts: tag_headless-client
  become: yes
  become_method: sudo
  strategy: free
  tasks:
    - include_role:
        name: headless_client
      vars:
        arma_host: 162.248.91.14
        arma_pass: "{{ ops_pass }}"
        a3sync_enabled: true
        a3sync_url: ftp://pdgmods.game.nfoservers.com
        a3sync_scheme: FTP
        a3sync_port: 21
        mods:
          - "@ace"
          - "@ace_cpr"
          - "@acex"
          - "@adr97"
          - "@advancedurbanrappelling"
          - "@alive"
          - "@asdg_jr"
          - "@asdga"
          - "@bc"
          - "@cba_a3"
          - "@cupcore"
          - "@cupcwa"
          - "@cupmaps"
          - "@em"
          - "@fhq_accessories"
          - "@fhq_weapons"
          - "@hafm"
          - "@inconeffectsv1.2"
          - "@jsrs"
          - "@lsd_nvg"
          - "@mrg_units_sfx"
          - "@mrt_accfncs"
          - "@popfor"
          - "@rz"
          - "@spec4gear"
          - "@stui"
          - "@task_force_radio"
          - "@tfw_radios"
          - "@tryk"
          - "@ultimate_soldier2mp"
          - "rhs/@rhsafrf"
          - "rhs/@rhsgref"
          - "rhs/@rhssaf"
          - "rhs/@rhsusaf"
