- hosts: tag_headless-client
  gather_facts: no

  tasks:
    - include_role:
        name: booted

- hosts: tag_headless-client
  become: yes
  become_method: sudo
  strategy: free
  tasks:
    - include_role:
        name: headless_client
      vars:
        arma_host: 66.151.244.237
        a3sync_url: ftp://pdgmods.game.nfoservers.com
        a3sync_scheme: FTP
        a3sync_port: 21
        mods:
          - "@ace"
          - "@ace_cpr"
          - "@advancedurbanrappelling"
          - "@ares"
          - "@bc"
          - "@cba_a3"
          - "@cup_tc"
          - "@em"
          - "@jsrs"
          - "@popfor"
          - "@spec4gear"
          - "@stui"
          - "@tryk"
          - "rhs/@rhsafaf"
          - "rhs/@rhsgref"
          - "rhs/@rhssaf"
          - "rhs/@rhsusaf"
