- name: pull the docker image from the Google Container Registry
  shell: "gcloud docker -- pull {{ docker_image }}"

- name: start client container
  docker_container:
    name: headless-client
    image: "{{ docker_image }}"
    volumes:
      - /opt/arma3:/arma3:rw
    env:
      ARMA_HOST: "{{ arma_host }}"
      ARMA_PASS: "{{ arma_pass }}"
      STEAM_USER: "{{ steam_user }}"
      STEAM_PASS: "{{ steam_pass }}"
    command: "{{ mods | format_mods_arg }}"
